### ISSUE TITLE
Mejora formulario

### ISSUE THREAD

**Issue by UrielMiranda** [cvallejo32/cvallejo32.github.io#1]
<img width="318" alt="Screen Shot 2022-05-01 at 2 15 26 PM" src="https://user-images.githubusercontent.com/12901838/166159011-52e08064-c238-4179-a679-cb8369352edf.png">

en esa parte de código debería agregarle los estilos de esta manera

```css
    .text-white{
     display: flex;
     flex-direction: column;
     justify-content: center;
}
```
